services:
  sentiment-api:
    build: .
    image: sentiment-analysis-api:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1  # Đảm bảo logs được hiển thị đúng cách
    volumes:
      - ./models:/app/models
    restart: unless-stopped
