services:
  sentiment-api:
    image: sentiment-analysis-app
    build: .
    ports:
      - "8000:8000"  # Đổi cổng từ 5000 thành 8000 cho FastAPI
    environment:
      - PYTHONUNBUFFERED=1  # Đảm bảo logs được hiển thị đúng cách
