global:
  resolve_timeout: 5m

route:
  receiver: 'default-receiver'
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h # How often to resend notifications for ongoing alerts

receivers:
  - name: 'default-receiver' # A default receiver
    # For real use, configure email, Slack, PagerDuty, webhook etc.
    # Example webhook (replace with your actual webhook or other config)
    # webhook_configs:
    # - url: 'http://some-webhook-receiver:PORT/path' 
    # For now, let's just log it. You'll see alerts in Alertmanager UI.

  - name: 'log-alerts' # Example to log alerts if you want to see them in console
    webhook_configs:
    - url: 'http://localhost:5001/' # Dummy, just for demonstration
      send_resolved: true

# Inhibition rules (optional)
# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match:
#       severity: 'warning'
#     # Don't send warning if critical alert with same labels is firing
#     equal: ['alertname', 'cluster', 'service']