server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml # Where Promtail stores its read positions

clients:
  - url: http://loki:3100/loki/api/v1/push # Loki service name

scrape_configs:
  - job_name: system # For host system logs (syslog, auth.log etc.)
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs # Label for these logs
          host: my-docker-host # You might want to make this dynamic if running on multiple hosts
          __path__: /var/log/*log # Path inside Promtail container (mounted from host)
    # You can add more specific syslog paths here, e.g., /var/log/syslog

  - job_name: containers # For Docker container logs
    docker_sd_configs: # Use Docker service discovery
      - host: unix:///var/run/docker.sock # Promtail needs access to Docker socket
        refresh_interval: 5s
        # You can filter which containers to scrape if needed
        # filters:
        #   - name: label
        #     values: ["logging=promtail"]
    relabel_configs: # Extract useful labels from Docker metadata
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_service_name'] # if using docker-compose service names
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_swarm_service_name']
        target_label: 'swarm_service' # if using Docker Swarm
      # Example to set a default "app" label for your FastAPI app's logs
      - source_labels: ['__meta_docker_container_name']
        regex: '/sentiment_app' # Match your app's container name
        action: replace
        target_label: 'app_name'
        replacement: 'sentiment_analysis_api'

  # If your app writes to a log file INSIDE its container (and you mount it to Promtail)
  # - job_name: app_file_logs
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: sentiment_app_file
  #         __path__: /app_container_logs/app.log # Path where Promtail can find the app's log file
  #         # This requires mounting the app's log directory to a volume shared with Promtail